config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :inscriptions
  resources :evaluations
  resources :cours
  resources :students
  resources :professeurs
  resources :class_rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "cours#index"
end

app/models/professeur.rb
class Professeur < ApplicationRecord
	
end

app/controllers/professeurs_controller.rb
class ProfesseursController < ApplicationController
  before_action :set_professeur, only: %i[ show edit update destroy ]

  # GET /professeurs or /professeurs.json
  def index
    @professeurs = Professeur.all
  end

  # GET /professeurs/1 or /professeurs/1.json
  def show
  end

  # GET /professeurs/new
  def new
    @professeur = Professeur.new
  end

  # GET /professeurs/1/edit
  def edit
  end

  # POST /professeurs or /professeurs.json
  def create
    @professeur = Professeur.new(professeur_params)

    respond_to do |format|
      if @professeur.save
        format.html { redirect_to @professeur, notice: "Professeur was successfully created." }
        format.json { render :show, status: :created, location: @professeur }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @professeur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professeurs/1 or /professeurs/1.json
  def update
    respond_to do |format|
      if @professeur.update(professeur_params)
        format.html { redirect_to @professeur, notice: "Professeur was successfully updated." }
        format.json { render :show, status: :ok, location: @professeur }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @professeur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professeurs/1 or /professeurs/1.json
  def destroy
    @professeur.destroy!

    respond_to do |format|
      format.html { redirect_to professeurs_path, status: :see_other, notice: "Professeur was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professeur
      @professeur = Professeur.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def professeur_params
      params.expect(professeur: [ :nom_professeur, :date_naissance, :numero_telephone, :email ])
    end
end

app/helpers/professeurs_helper.rb
module ProfesseursHelper
end

app/views/professeurs/_form.html.erb
<%= form_with(model: professeur) do |form| %>
  <% if professeur.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(professeur.errors.count, "error") %> prohibited this professeur from being saved:</h2>

      <ul>
        <% professeur.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nom_professeur, style: "display: block" %>
    <%= form.text_field :nom_professeur %>
  </div>

  <div>
    <%= form.label :date_naissance, style: "display: block" %>
    <%= form.date_field :date_naissance %>
  </div>

  <div>
    <%= form.label :numero_telephone, style: "display: block" %>
    <%= form.text_field :numero_telephone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/professeurs/_professeur.html.erb
<div id="<%= dom_id professeur %>">
  <p>
    <strong>Nom professeur:</strong>
    <%= professeur.nom_professeur %>
  </p>

  <p>
    <strong>Date naissance:</strong>
    <%= professeur.date_naissance %>
  </p>

  <p>
    <strong>Numero telephone:</strong>
    <%= professeur.numero_telephone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= professeur.email %>
  </p>

</div>

app/views/professeurs/edit.html.erb
<% content_for :title, "Editing professeur" %>

<h1>Editing professeur</h1>

<%= render "form", professeur: @professeur %>

<br>

<div>
  <%= link_to "Show this professeur", @professeur %> |
  <%= link_to "Back to professeurs", professeurs_path %>
</div>

app/views/professeurs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Professeurs" %>

<h1>Professeurs</h1>

<table>
  <thead>
    <tr>
      <th>Nom_professeur</th>
      <th>Date_naissance</th>
      <th>Numero_telephone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professeurs.each do |professeur| %>
      <tr>
        <td><%= professeur.nom_professeur %></td>
        <td><%= professeur.date_naissance %></td>
        <td><%= professeur.numero_telephone %></td>
        <td><%= professeur.email %></td>
        <td><%= link_to 'Show', professeur %></td>
        <td><%= link_to 'Edit', edit_professeur_path(professeur) %></td>
        <td><%= link_to 'Destroy', professeur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to "New professeur", new_professeur_path %>

app/views/professeurs/new.html.erb
<% content_for :title, "New professeur" %>

<h1>New professeur</h1>

<%= render "form", professeur: @professeur %>

<br>

<div>
  <%= link_to "Back to professeurs", professeurs_path %>
</div>

app/views/professeurs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @professeur %>

<div>
  <%= link_to "Edit this professeur", edit_professeur_path(@professeur) %> |
  <%= link_to "Back to professeurs", professeurs_path %>

  <%= button_to "Destroy this professeur", @professeur, method: :delete %>
</div>