config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :inscriptions
  resources :evaluations
  resources :cours
  resources :students
  resources :professeurs
  resources :class_rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "cours#index"
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :professeur
	has_many :cour
	has_many :class_room
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_path, status: :see_other, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.expect(student: [ :nom_student, :date_naissance, :numero_telephone, :email, :grade, :numero_parents, :cours_id, :professeur_id, :class_room_id ])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nom_student, style: "display: block" %>
    <%= form.text_field :nom_student %>
  </div>

  <div>
    <%= form.label :date_naissance, style: "display: block" %>
    <%= form.date_field :date_naissance %>
  </div>

  <div>
    <%= form.label :numero_telephone, style: "display: block" %>
    <%= form.text_field :numero_telephone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :grade, style: "display: block" %>
    <%= form.text_field :grade %>
  </div>

  <div>
    <%= form.label :numero_parents, style: "display: block" %>
    <%= form.text_field :numero_parents %>
  </div>

  <div>
    <%= form.label :cours_id, style: "display: block" %>
    <%= form.text_field :cours_id %>
  </div>

  <div>
    <%= form.label :professeur_id, style: "display: block" %>
    <%= form.text_field :professeur_id %>
  </div>

  <div>
    <%= form.label :class_room_id, style: "display: block" %>
    <%= form.text_field :class_room_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Nom student:</strong>
    <%= student.nom_student %>
  </p>

  <p>
    <strong>Date naissance:</strong>
    <%= student.date_naissance %>
  </p>

  <p>
    <strong>Numero telephone:</strong>
    <%= student.numero_telephone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

  <p>
    <strong>Grade:</strong>
    <%= student.grade %>
  </p>

  <p>
    <strong>Numero parents:</strong>
    <%= student.numero_parents %>
  </p>

  <p>
    <strong>Cours:</strong>
    <%= student.cours_id %>
  </p>

  <p>
    <strong>Professeur:</strong>
    <%= student.professeur_id %>
  </p>

  <p>
    <strong>Class room:</strong>
    <%= student.class_room_id %>
  </p>

</div>

app/views/students/edit.html.erb
<% content_for :title, "Editing student" %>

<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Students" %>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Nom_student</th>
      <th>Date_naissance</th>
      <th>Numero_telephone</th>
      <th>Email</th>
      <th>Grade</th>
      <th>Numero_parents</th>
      <th>Cours_id</th>
      <th>Professeur_id</th>
      <th>Class_room_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.nom_student %></td>
        <td><%= student.date_naissance %></td>
        <td><%= student.numero_telephone %></td>
        <td><%= student.email %></td>
        <td><%= student.grade %></td>
        <td><%= student.numero_parents %></td>
        <td><%= student.cours_id %></td>
        <td><%= student.professeur_id %></td>
        <td><%= student.class_room_id %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<% content_for :title, "New student" %>

<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>