config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :inscriptions
  resources :evaluations
  resources :cours
  resources :students
  resources :professeurs
  resources :class_rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "cours#index"
end

app/models/class_room.rb
class ClassRoom < ApplicationRecord
	belongs_to :professeur
	belongs_to :cour, class_name: "Cour", foreign_key: :cours_id
end

app/controllers/class_rooms_controller.rb
class ClassRoomsController < ApplicationController
  before_action :set_class_room, only: %i[ show edit update destroy ]

  # GET /class_rooms or /class_rooms.json
  def index
    @class_rooms = ClassRoom.all
  end

  # GET /class_rooms/1 or /class_rooms/1.json
  def show
  end

  # GET /class_rooms/new
  def new
    @class_room = ClassRoom.new
  end

  # GET /class_rooms/1/edit
  def edit
  end

  # POST /class_rooms or /class_rooms.json
  def create
    @class_room = ClassRoom.new(class_room_params)

    respond_to do |format|
      if @class_room.save
        format.html { redirect_to @class_room, notice: "Class room was successfully created." }
        format.json { render :show, status: :created, location: @class_room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @class_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_rooms/1 or /class_rooms/1.json
  def update
    respond_to do |format|
      if @class_room.update(class_room_params)
        format.html { redirect_to @class_room, notice: "Class room was successfully updated." }
        format.json { render :show, status: :ok, location: @class_room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @class_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_rooms/1 or /class_rooms/1.json
  def destroy
    @class_room.destroy!

    respond_to do |format|
      format.html { redirect_to class_rooms_path, status: :see_other, notice: "Class room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_room
      @class_room = ClassRoom.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def class_room_params
      params.expect(class_room: [ :numero_classe, :professeur_id, :cours_id ])
    end
end

app/helpers/class_rooms_helper.rb
module ClassRoomsHelper
end

app/views/class_rooms/_class_room.html.erb
<div id="<%= dom_id class_room %>">
  <p>
    <strong>Numero classe:</strong>
    <%= class_room.numero_classe %>
  </p>

  <p>
    <strong>Professeur:</strong>
    <%= class_room.professeur_id %>
  </p>

  <p>
    <strong>Cours:</strong>
    <%= class_room.cours_id %>
  </p>

</div>

app/views/class_rooms/_form.html.erb
<%= form_with(model: class_room) do |form| %>
  <% if class_room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(class_room.errors.count, "error") %> prohibited this class_room from being saved:</h2>

      <ul>
        <% class_room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :numero_classe, style: "display: block" %>
    <%= form.text_field :numero_classe %>
  </div>

  <div>
    <%= form.label :professeur_id, style: "display: block" %>
    <%= form.text_field :professeur_id %>
  </div>

  <div>
    <%= form.label :cours_id, style: "display: block" %>
    <%= form.text_field :cours_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/class_rooms/edit.html.erb
<% content_for :title, "Editing class room" %>

<h1>Editing class room</h1>

<%= render "form", class_room: @class_room %>

<br>

<div>
  <%= link_to "Show this class room", @class_room %> |
  <%= link_to "Back to class rooms", class_rooms_path %>
</div>

app/views/class_rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Class rooms" %>

<h1>Class rooms</h1>

<table>
  <thead>
    <tr>
      <th>numero_classe</th>
      <th>professeur_id</th>
      <th>cours_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @class_rooms.each do |class_room| %>
      <tr>
        <td><%= class_room.numero_classe %></td>
        <td><%= class_room.professeur_id %></td>
        <td><%= class_room.cours_id %></td>
        <td><%= link_to 'Show', class_room %></td>
        <td><%= link_to 'Edit', edit_class_room_path(class_room) %></td>
        <td><%= link_to 'Destroy', class_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New class room", new_class_room_path %>

app/views/class_rooms/new.html.erb
<% content_for :title, "New class room" %>

<h1>New class room</h1>

<%= render "form", class_room: @class_room %>

<br>

<div>
  <%= link_to "Back to class rooms", class_rooms_path %>
</div>

app/views/class_rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @class_room %>

<div>
  <%= link_to "Edit this class room", edit_class_room_path(@class_room) %> |
  <%= link_to "Back to class rooms", class_rooms_path %>

  <%= button_to "Destroy this class room", @class_room, method: :delete %>
</div>